CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER(5) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) UNIQUE NOT NULL
);

INSERT INTO CATEGORY VALUES (1, 'Electronics');
INSERT INTO CATEGORY VALUES (2, 'Mobiles');
INSERT INTO CATEGORY VALUES (3, 'Laptops');
INSERT INTO CATEGORY VALUES (4, 'Fashion');
INSERT INTO CATEGORY VALUES (5, 'Footwear');
INSERT INTO CATEGORY VALUES (6, 'Beauty');
INSERT INTO CATEGORY VALUES (7, 'Home Appliances');
INSERT INTO CATEGORY VALUES (8, 'Watches');
INSERT INTO CATEGORY VALUES (9, 'Accessories');
INSERT INTO CATEGORY VALUES (10, 'Grocery');

COMMIT;

CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(5) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    PRICE NUMBER(10,2) NOT NULL,
    STOCK NUMBER(5) NOT NULL,
    CATEGORY_ID NUMBER(5),
    CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO PRODUCT VALUES
(101, 'Samsung Galaxy S24', 'Latest Samsung smartphone', 69999.00, 15, 2);

INSERT INTO PRODUCT VALUES
(102, 'iPhone 15', 'Apple smartphone with advanced camera', 69999.00, 10, 2);

INSERT INTO PRODUCT VALUES
(103, 'HP Pavilion Laptop', 'HP laptop for everyday use', 54999.00, 12, 3);

INSERT INTO PRODUCT VALUES
(104, 'Nike Running Shoes', 'Comfortable running shoes', 3999.00, 25, 5);

INSERT INTO PRODUCT VALUES
(105, 'Lakme Face Cream', 'Moisturizing face cream', 899.00, 30, 6);

INSERT INTO PRODUCT VALUES
(106, 'Samsung Smart TV', 'Smart LED television', 45999.00, 8, 1);

INSERT INTO PRODUCT VALUES
(107, 'Fastrack Watch', 'Stylish analog wrist watch', 1299.00, 20, 8);

INSERT INTO PRODUCT VALUES
(108, 'HP Laptop Bag', 'Durable laptop carrying bag', 1499.00, 18, 9);

INSERT INTO PRODUCT VALUES
(109, 'Levis Casual Shirt', 'Comfortable casual shirt', 2499.00, 20, 4);

INSERT INTO PRODUCT VALUES
(110, 'Philips Mixer Grinder', 'Kitchen mixer grinder', 3499.00, 14, 7);

COMMIT;

SELECT * FROM PRODUCT;

SELECT * FROM CATEGORY;

UPDATE PRODUCT
SET PRICE = 64999.00,
    STOCK = 15
WHERE PRODUCT_ID = 102;

COMMIT;

DELETE FROM PRODUCT
WHERE PRODUCT_ID = 110;

COMMIT;

SELECT C.CATEGORY_NAME,
       P.PRODUCT_NAME,
       P.PRICE,
       P.STOCK
FROM CATEGORY C
JOIN PRODUCT P
ON C.CATEGORY_ID = P.CATEGORY_ID
ORDER BY C.CATEGORY_NAME;

SELECT C.CATEGORY_NAME,
       P.PRODUCT_NAME,
       P.PRICE,
       P.STOCK
FROM CATEGORY C
JOIN PRODUCT P
ON C.CATEGORY_ID = P.CATEGORY_ID
WHERE C.CATEGORY_NAME = 'Mobiles';

SELECT C.CATEGORY_NAME,
       COUNT(P.PRODUCT_ID) AS PRODUCT_COUNT
FROM CATEGORY C
LEFT JOIN PRODUCT P
ON C.CATEGORY_ID = P.CATEGORY_ID
GROUP BY C.CATEGORY_NAME
ORDER BY C.CATEGORY_NAME;