CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    REVIEW_TEXT VARCHAR2(500) NOT NULL,
    REVIEW_DATE DATE NOT NULL
);


CREATE TABLE RATING (
    RATING_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    RATING NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
    RATING_DATE DATE NOT NULL
);


INSERT INTO REVIEW (REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_TEXT, REVIEW_DATE)
VALUES (11, 111, 207, 'Excellent product and very useful', SYSDATE);

INSERT INTO REVIEW (REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_TEXT, REVIEW_DATE)
VALUES (12, 112, 207, 'Good product and worth the price', SYSDATE);

INSERT INTO REVIEW (REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_TEXT, REVIEW_DATE)
VALUES (13, 113, 208, 'Amazing quality and fast delivery', SYSDATE);

INSERT INTO REVIEW (REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_TEXT, REVIEW_DATE)
VALUES (14, 114, 208, 'Good quality product', SYSDATE);

INSERT INTO REVIEW (REVIEW_ID, CUSTOMER_ID, PRODUCT_ID, REVIEW_TEXT, REVIEW_DATE)
VALUES (15, 115, 209, 'Product is okay but could be better', SYSDATE);

COMMIT;


INSERT INTO RATING (RATING_ID, CUSTOMER_ID, PRODUCT_ID, RATING, RATING_DATE)
VALUES (16, 116, 210, 5, SYSDATE);

INSERT INTO RATING (RATING_ID, CUSTOMER_ID, PRODUCT_ID, RATING, RATING_DATE)
VALUES (17, 117, 210, 4, SYSDATE);

INSERT INTO RATING (RATING_ID, CUSTOMER_ID, PRODUCT_ID, RATING, RATING_DATE)
VALUES (18, 118, 211, 5, SYSDATE);

INSERT INTO RATING (RATING_ID, CUSTOMER_ID, PRODUCT_ID, RATING, RATING_DATE)
VALUES (19, 119, 211, 4, SYSDATE);

INSERT INTO RATING (RATING_ID, CUSTOMER_ID, PRODUCT_ID, RATING, RATING_DATE)
VALUES (20, 120, 212, 3, SYSDATE);

COMMIT;


SELECT 
    R.REVIEW_ID,
    R.CUSTOMER_ID,
    R.PRODUCT_ID,
    P.PRODUCT_NAME,
    R.REVIEW_TEXT,
    R.REVIEW_DATE
FROM REVIEW R
JOIN PRODUCT P ON R.PRODUCT_ID = P.PRODUCT_ID
ORDER BY R.REVIEW_DATE DESC;


SELECT 
    PRODUCT_ID,
    ROUND(AVG(RATING), 2) AS AVERAGE_RATING
FROM RATING
GROUP BY PRODUCT_ID
ORDER BY AVERAGE_RATING DESC;


SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    ROUND(AVG(R.RATING), 2) AS AVERAGE_RATING
FROM RATING R
JOIN PRODUCT P ON R.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
HAVING AVG(R.RATING) >= 4
ORDER BY AVERAGE_RATING DESC;
