CREATE TABLE SELLER (
    SELLER_ID NUMBER(5) PRIMARY KEY,
    SELLER_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    GST_NUMBER VARCHAR2(20) UNIQUE
);


INSERT INTO SELLER
VALUES (101, 'ABC Electronics', 'abc@gmail.com', 'GST101');

INSERT INTO SELLER
VALUES (102, 'Fashion World', 'fashion@gmail.com', 'GST102');

INSERT INTO SELLER
VALUES (103, 'Tech Store', 'tech@gmail.com', 'GST103');

COMMIT;

SELECT * FROM SELLER;



CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER(5) PRIMARY KEY,
    SELLER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    STOCK_QUANTITY NUMBER(5) NOT NULL,
    AVAILABILITY_STATUS VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_INVENTORY_SELLER
    FOREIGN KEY (SELLER_ID)
    REFERENCES SELLER(SELLER_ID)
);


INSERT INTO INVENTORY
VALUES (1, 101, 201, 25, 'Available');

INSERT INTO INVENTORY
VALUES (2, 101, 202, 0, 'Unavailable');

INSERT INTO INVENTORY
VALUES (3, 102, 203, 15, 'Available');

COMMIT;

SELECT * FROM INVENTORY;